USE QL_BANHANG
INSERT INTO LOAIAMTHUC VALUES('1','Wonder Bread');
INSERT INTO LOAIAMTHUC VALUES('2','Olymel');
INSERT INTO LOAIAMTHUC VALUES('3','Cobblestone');
INSERT INTO LOAIAMTHUC VALUES('4','Dr. Oetker');
INSERT INTO LOAIAMTHUC VALUES('5','Taco Bell');
INSERT INTO LOAIAMTHUC VALUES('6','Lavazza');
INSERT INTO LOAIAMTHUC VALUES('7','Bewleys');
INSERT INTO LOAIAMTHUC VALUES('8','Olymel');
INSERT INTO LOAIAMTHUC VALUES('9','Burger King');
INSERT INTO LOAIAMTHUC VALUES('10','Nesquik');
INSERT INTO LOAIAMTHUC VALUES('11','Lavazza');
INSERT INTO LOAIAMTHUC VALUES('12','Pizza Hut');
INSERT INTO LOAIAMTHUC VALUES('13','Soprole');
INSERT INTO LOAIAMTHUC VALUES('14','Baskin robbins');
INSERT INTO LOAIAMTHUC VALUES('15','Bewleys');
INSERT INTO LOAIAMTHUC VALUES('16','Tic Tac');
INSERT INTO LOAIAMTHUC VALUES('17','Andy Capps fries');
INSERT INTO LOAIAMTHUC VALUES('18','Bel Group');
INSERT INTO LOAIAMTHUC VALUES('19','Lavazza');
INSERT INTO LOAIAMTHUC VALUES('20','Dunkin Donuts');

