USE QL_BANHANG_TRANHCHAP
GO 

--Thêm thông tin hoa hồng

--Thêm khách hàng--
GO
CREATE PROC sp_ThemKhachHang
	@MANGUOIDUNG CHAR(10),
	@EMAIL VARCHAR(50),
	@TEN NVARCHAR(50),
	@SDT CHAR(10),
	@HINHANHND  BIT,
	@DIACHIHINHANHND VARCHAR(100),
	@MASTKNGANHANG CHAR(10),
	@MATK CHAR(10),
	@MADIACHI CHAR(10),
	@SODUVI INT

AS
BEGIN TRAN
	
	INSERT INTO KHACHHANG
	VALUES
		(@MANGUOIDUNG, @EMAIL, @TEN, @SDT, @HINHANHND, @DIACHIHINHANHND, @MASTKNGANHANG, @MATK, @MADIACHI, @SODUVI)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm tài khoản--
CREATE PROC sp_ThemTaiKhoan
	@MATK CHAR(10), 
	@TENTK VARCHAR(50),
	@TINHTRANGTK NVARCHAR(30),
	@MATKHAUTK VARCHAR(50),
	@LOAITK INT
AS
BEGIN TRAN
	

	INSERT INTO TAIKHOAN
	VALUES
		(@MATK, @TENTK, @TINHTRANGTK, @MATKHAUTK, @LOAITK)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG KHÔNG TẠO TÀI KHOẢN ĐƯỢC'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm ngân hàng--
CREATE PROC sp_ThemNganHang
	@MASTKNGANHANG CHAR(10),
	@TENNGANHANG NVARCHAR(50),
	@TENCHINHANH NVARCHAR(50),
	@STK CHAR(13)
AS
BEGIN TRAN
	

	INSERT INTO NGANHANG
	VALUES
		(@MASTKNGANHANG, @TENNGANHANG, @TENCHINHANH, @STK)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm đơn đặt hàng--
CREATE PROC sp_ThemDonDH
	@MADH CHAR(10),
	@TRANGTHAIDH NCHAR(20),
	@NGAYLAP DATE,
	@HINHTHUCTT NCHAR(20),
	@PHISP int,
	@PHIVANCHUYEN int,
	@MADCGH CHAR(10),
	@MAKH CHAR(10),
	@MACN CHAR(10),
	@MATX CHAR(10),
	@MAKHUVUC CHAR(10)

AS
BEGIN TRAN
	
	INSERT INTO DON_DH
	VALUES
		(@MADH, @TRANGTHAIDH, @NGAYLAP, @HINHTHUCTT, @PHISP, @PHIVANCHUYEN, @MADCGH, @MAKH, @MACN,  @MATX, @MAKHUVUC)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm đánh giá chi nhánh--
CREATE PROC sp_ThemDanhGiaChiNhanh
	@MADH CHAR(10),
	@RATING FLoat,
	@NOIDUNG NVARCHAR(100),
	@MACN CHAR(10),
	@MADT CHAR(10)

AS
BEGIN TRAN
	
	
	INSERT INTO DANHGIA_CHINHANH
	VALUES
		(@MADH, @RATING, @NOIDUNG, @MACN, @MADT)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm đánh giá món ăn--
CREATE PROC sp_ThemDanhGiaMonAn
	@MADH CHAR(10),
	@MAMONAN CHAR(10),
	@RATING FLoat,
	@NOIDUNG NVARCHAR(100)
AS
BEGIN TRAN
	
	INSERT INTO DANHGIA_MONAN
	VALUES
		(@MADH, @MAMONAN, @RATING, @NOIDUNG)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm đánh giá tài xế--
CREATE PROC sp_ThemDanhGiaTaiXe
	@MADH CHAR(10),
	@MATX CHAR(10),
	@RATING FLoat,
	@NOIDUNG NVARCHAR(100)

AS
BEGIN TRAN
	
	
	INSERT INTO DANHGIA_TX
	VALUES
		(@MADH, @MATX, @RATING, @NOIDUNG)
	IF @@ERROR <>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm địa chỉ--
CREATE PROC sp_ThemDiaChi
	@MADIACHI CHAR(10),
	@DIACHI NVARCHAR(50),
	@MAPHUONG CHAR(10)
AS
BEGIN TRAN
	

	INSERT INTO DIACHI
	VALUES
		(@MADIACHI, @DIACHI, @MAPHUONG)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO	

--Thêm phường--
CREATE PROC sp_ThemPhuong
	@MAPHUONG CHAR(10),
	@TENPHUONG NVARCHAR(50),
	@MAHUYEN CHAR(10)
AS
BEGIN TRAN


	INSERT INTO PHUONG
	VALUES
		(@MAPHUONG, @TENPHUONG, @MAHUYEN)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm quận huyện--
CREATE PROC sp_ThemQuanHuyen
	@MAHUYEN CHAR(10),
	@TENHUYEN NVARCHAR(50),
	@MAKHUVUC CHAR(10)
AS
BEGIN TRAN
	

	INSERT INTO QUAN_HUYEN
	VALUES
		(@MAHUYEN, @TENHUYEN, @MAKHUVUC)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm khu vực--
CREATE PROC sp_ThemKhuVuc
	@MAKHUVUC CHAR(10),
	@TENKHUVUC NVARCHAR(50),
	@MACUOC CHAR(10)
AS
BEGIN TRAN
	

	INSERT INTO KHUVUC
	VALUES
		(@MAKHUVUC, @TENKHUVUC, @MACUOC)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm giá cước--
CREATE PROC sp_ThemGiaCuoc
	@MACUOC CHAR(10),
	@GIACUOC INT,
	@KHOANGCACH INT,
	@THOIGIANHIEULUC DATETIME,
	@DONVITIEN CHAR(10),
	@MAQTV CHAR(10)
AS
BEGIN TRAN
	
	DECLARE @NGAYTAO DATE = GETDATE()
	INSERT INTO GIACUOC
	VALUES
		(@MACUOC, @GIACUOC, @KHOANGCACH, @NGAYTAO, @THOIGIANHIEULUC, @DONVITIEN, @MAQTV)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm tài xế--
CREATE PROC sp_ThemTaiXe
	@MATX CHAR(10),
	@EMAIL VARCHAR(50),
	@TEN NVARCHAR(50),
	@SDT CHAR(10),
	@HINHANHND BIT,
	@DIACHIHINHANHND VARCHAR(100),
	@MATKNGANHANG CHAR(10),
	@MATK CHAR(10),
	@MADIACHI CHAR(10),
	@BIENSOXE CHAR(10),
	@PHITHECHAN INT,
	@CMND CHAR(12),
	@MAKHUVUCHD CHAR(10)
	
AS
BEGIN TRAN
	
	

	INSERT INTO TAIXE
	VALUES
		(@MATX, @EMAIL,@TEN, @HINHANHND, @DIACHIHINHANHND, @SDT, @BIENSOXE, @PHITHECHAN,@CMND, @MAKHUVUCHD,@MATKNGANHANG, @MATK,@MADIACHI)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI KHÔNG TẠO ĐƯỢC TÀI XẾ'
		ROLLBACK TRAN
		RETURN
	END 
	
COMMIT TRAN
return 
GO

--Thêm quản trị viên
CREATE PROC sp_ThemQuanTriVien
	@MAQTV CHAR(10),
	@EMAIL VARCHAR(50),
	@TEN NVARCHAR(50),
	@SDT CHAR(10),
	@HINHANHND BIT,
	@DIACHIHINHANHND VARCHAR(100),
	@MATKNGANHANG CHAR(10),
	@MATK CHAR(10),
	@MADIACHI CHAR(10),
	@LUONGQTV INT

AS
BEGIN TRAN
	
	
	INSERT INTO QUANTRIVIEN
	VALUES
		(@MAQTV, @EMAIL, @MATK, @TEN, @SDT, @HINHANHND, @DIACHIHINHANHND, @LUONGQTV, @MATKNGANHANG, @MADIACHI)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm quyền thao tác--
CREATE PROC sp_ThemQuyenThaoTac
	@MAQTV CHAR(10),
	@MATK CHAR(10),
	@MATHAOTAC CHAR(10),
	@MATHUOCTINH CHAR(10),
	@DUOCPHEP BIT
AS
BEGIN TRAN
	

	INSERT INTO QUYENTHAOTAC
	VALUES
		(@MAQTV, @MATK, @MATHAOTAC, @MATHUOCTINH, @DUOCPHEP)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm thao tác--
CREATE PROC sp_ThemThaoTac
	@MATHAOTAC CHAR(10),
	@TENTHAOTAC NCHAR(20)
AS
BEGIN TRAN
	

	INSERT INTO THAOTAC
	VALUES
		(@MATHAOTAC, @TENTHAOTAC)
	IF @@ERROR<>0 
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm thuộc tính--
CREATE PROC sp_ThemThuocTinh
	@MATHUOCTINH CHAR(10),
	@TENTHUOCTINH NCHAR(20),
	@MAPHAMVI CHAR(10)
AS
BEGIN TRAN
	

	INSERT INTO THUOCTINH
	VALUES
		(@MATHUOCTINH, @TENTHUOCTINH, @MAPHAMVI)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm phạm vi bảng--
CREATE PROC sp_ThemPhamViBang
	@MAPHAMVI CHAR(10),
	@TENPHAMVI NCHAR(20),
	@IDMAX int
AS
BEGIN TRAN
	

	INSERT INTO PHAMVIBANG
	VALUES
		(@MAPHAMVI, @TENPHAMVI, @IDMAX)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm nhân viên--
CREATE PROC sp_ThemNhanVien
	@MANHANVIEN CHAR(10) ,
	@EMAIL VARCHAR(50),
	@TEN NVARCHAR(20),
	@SDT CHAR(10),
	@HINHANHND BIT,
	@DIACHIHINHANHND VARCHAR(100),
	@MATKNGANHANG CHAR(10),
	@MATK CHAR(10),
	@MADIACHI CHAR(10),
	@LUONGNV MONEY
AS
BEGIN TRAN 
	
	DECLARE @NGAYTG DATE = GETDATE()
	INSERT INTO NHANVIEN
	VALUES
		(@MANHANVIEN, @EMAIL, @TEN, @SDT, @HINHANHND, @DIACHIHINHANHND, @NGAYTG, @LUONGNV, @MATKNGANHANG, @MATK, @MADIACHI)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm hợp đồng--
CREATE PROC sp_ThemHopDong
	@MAHD CHAR(10),
	@SL_CN_DK INT,
	@PHIKH INT,
	@MADOITAC CHAR(10)


AS
BEGIN TRAN 
	
	DECLARE @NGAYLAP DATE = GETDATE()
	INSERT INTO HOPDONG
	VALUES
		(@MAHD, @SL_CN_DK, @NGAYLAP, @PHIKH, @MADOITAC)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm thông tin hợp đồng--
CREATE PROC sp_ThemThongTinHopDong
	@MAHD CHAR(10),
	@STT int,
	@THOIHAN int,
	@TGBD DATE,
	@TGHH DATE,
	@MAHH CHAR(10),
	@MANV CHAR(10)

AS
BEGIN TRAN 
	
	
	INSERT INTO THONGTIN_HOPDONG
	VALUES
		(@MAHD, @STT, @THOIHAN,@TGBD, @TGHH, @MAHH,@MANV)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm đối tác--
CREATE PROC sp_ThemDoiTac
	@MADOITAC CHAR(10),
	@EMAILDT CHAR(50),
	@TENDT NCHAR(50),
	@SDTDT CHAR(10),
	@HINHANHND  BIT,
	@DIACHIHINHANHND CHAR(300),
	@MATKNGANHANG CHAR(10),
	@MATK CHAR(10),
	@MADIACHI CHAR(10),
	@MSTHUE CHAR(10),
	@MAIL_NDD CHAR(50),
	@SLDUKIENMIN INT,
	@SLDUKIENMAX INT

AS
BEGIN TRAN 
	
	INSERT INTO DOITAC
	VALUES
		(@MADOITAC, @EMAILDT, @TENDT, @HINHANHND, @DIACHIHINHANHND, @SDTDT, @MSTHUE,	@MAIL_NDD, @SLDUKIENMIN, @SLDUKIENMAX, @MATKNGANHANG, @MATK, @MADIACHI)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm loại ẩm thực - đối tác
CREATE PROC sp_ThemLoaiAmThucDoiTac
	@MALAT CHAR(10), 
	@MADT CHAR(10)

AS
BEGIN TRAN 
	

	INSERT INTO LOAIAMTHUCDOITAC
	VALUES
		(@MALAT, @MADT)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm chi nhánh--
CREATE PROC sp_ThemChiNhanh
	@MACN CHAR(10),
	@SDT_CN CHAR(10),
	@HINHANHND  BIT,
	@DIACHIHINHANHND CHAR(300),
	@MATKNGANHANG CHAR(10),
	@MATK CHAR(10),
	@MADIACHI CHAR(10),
	@MADT CHAR(10)

AS
BEGIN TRAN 
	
	
	INSERT INTO CHINHANH
	VALUES
		(@MACN,@HINHANHND,@DIACHIHINHANHND,	@SDT_CN, @MATK, @MATKNGANHANG,	@MADIACHI,  @MADT)
	IF @@ERROR <>0
	BEGIN
		RAISERROR ('KHONG THEM CHI NHANH DUOC',16,1)
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm hợp đồng - chi nhánh--
CREATE PROC sp_ThemHopDongChiNhanh
	@MACN CHAR(10),
	@MAHD CHAR(10)

AS
BEGIN TRAN 
	

	INSERT INTO HOPDONGCHINHANH
	VALUES
		(@MACN, @MAHD)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm cửa hàng--
CREATE PROC sp_ThemCuaHang
	@MACN CHAR(10),
	@TENCH NVARCHAR(20),
	@TG_HD_MO TIME,
	@TG_HD_DONG TIME,
	@TINHTRANGCH NCHAR(20)


AS
BEGIN TRAN 
	
	
	INSERT INTO CUAHANG
	VALUES
		(@MACN,	@TENCH,	@TG_HD_MO, @TG_HD_DONG, @TINHTRANGCH)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO


GO


--Thêm tùy chọn món ăn--
CREATE PROC sp_ThemTuyChonMonAn
	@MATUYCHON CHAR(10),
	@TENTUYCHON NCHAR(20),
	@MUCDO NCHAR(20),
	@MAMONAN CHAR(10)

AS
BEGIN TRAN 
	

	INSERT INTO TUYCHONMONAN
	VALUES
		(@MATUYCHON, @TENTUYCHON, @MUCDO, @MAMONAN)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm thực đơn đặt hàng--
CREATE PROC sp_ThemThucDonDatHang
	@MAMONAN CHAR(10),
	@MADH CHAR(10),
	@SOLUONG INT

AS
BEGIN TRAN 

	DECLARE @GIABAN INT
	SELECT @GIABAN=GIA FROM THUCDON WHERE MAMONAN=@MAMONAN
	INSERT INTO THUCDONDATHANG
	VALUES
		(@MAMONAN, @MADH, @GIABAN, @SOLUONG)
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRAN
		RAISERROR ('KHONG THEM MON VAO THUC DON DUOC',16,1)
		RETURN
	END
	UPDATE DON_DH SET PHISP=PHISP+@GIABAN*@SOLUONG WHERE MADH=@MADH
	IF @@ERROR<>0
	BEGIN
		ROLLBACK TRAN
		RAISERROR ('KHONG THEM MON VAO THUC DON DUOC',16,1)
		RETURN
	END
	
COMMIT TRAN
RETURN
GO

--Thêm tùy chọn món đặt hàng--
CREATE PROC sp_ThemTuyChonMonDatHang
	@MATUYCHON CHAR(10),
	@MADH CHAR(10)

AS
BEGIN TRAN 
	
	IF ((SELECT TD.TINHTRANG
		FROM TUYCHONMONDATHANG TCMDH
		JOIN TUYCHONMONAN TCMA
		ON TCMDH.MATUYCHON = TCMA.MATUYCHON
		JOIN THUCDON TD
		ON TCMA.MAMONAN = TD.MAMONAN) = 'Hết hàng')
	BEGIN
		PRINT N'Món này hiện đã ngừng bán'
		ROLLBACK TRAN
		RETURN
	END
	INSERT INTO TUYCHONMONDATHANG
	VALUES
		(@MATUYCHON, @MADH)
	
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO
USE master
GO