USE QL_BANHANG
GO 

--Thêm khách hàng--
GO
CREATE PROC sp_ThemKhachHang
	@MANGUOIDUNG VARCHAR(10),
	@EMAIL VARCHAR(50),
	@TEN NVARCHAR(50),
	@SDT VARCHAR(10),
	@NGAYTG DATETIME,
	@HINHANHND  BIT,
	@DIACHIHINHANHND VARCHAR(100),
	@MASTKNGANHANG VARCHAR(10),
	@MATK VARCHAR(10),
	@MADIACHI VARCHAR(10),
	@DIACHI NVARCHAR(50),
	@SODUVI INT

AS
BEGIN TRAN
	BEGIN TRY
	INSERT INTO KHACHHANG
	VALUES
		(@MANGUOIDUNG, @EMAIL, @TEN, @SDT, @NGAYTG, @HINHANHND, @DIACHIHINHANHND, @MASTKNGANHANG, @MATK, @DIACHI, @MADIACHI, @SODUVI)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm tài khoản--
CREATE PROC sp_ThemTaiKhoan
	@MATK VARCHAR(10), 
	@TENTK VARCHAR(50),
	@TINHTRANGTK NVARCHAR(30),
	@MATKHAUTK VARCHAR(50),
	@NGAYTG DATETIME,
	@LOAITK INT
AS
BEGIN TRAN
	

	INSERT INTO TAIKHOAN
	VALUES
		(@MATK, @TENTK, @TINHTRANGTK, @MATKHAUTK,@NGAYTG, @LOAITK)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG KHÔNG TẠO TÀI KHOẢN ĐƯỢC'
		ROLLBACK TRAN
		RETURN 1
	END 
COMMIT TRAN
return 0
GO

--Thêm ngân hàng--
CREATE PROC sp_ThemNganHang
	@MASTKNGANHANG VARCHAR(10),
	@TENNGANHANG NVARCHAR(50),
	@TENCHINHANH NVARCHAR(50),
	@STK CHAR(13)
AS
BEGIN TRAN
	

	INSERT INTO NGANHANG
	VALUES
		(@MASTKNGANHANG, @TENNGANHANG, @TENCHINHANH, @STK)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm đơn đặt hàng--
CREATE PROC sp_ThemDonDH
	@MADH VARCHAR(10),
	@TRANGTHAIDH NCHAR(20),
	@NGAYLAP DATETIME, 
	@HINHTHUCTT NCHAR(20),
	@PHISP int,
	@PHIVANCHUYEN int,
	@MAKH VARCHAR(10),
	@TENKH NVARCHAR(50),
	@SDTKH VARCHAR(10),
	@MADCGH VARCHAR(10),
	@DIACHIGH NVARCHAR(50),
	@MACN VARCHAR(10),
	@TENCN NCHAR(20),
	@DIACHICN NVARCHAR(50),
	@MADT VARCHAR(10),
	@PTHH INT,
	@MATX VARCHAR(10),
	@TENTX NVARCHAR(50),
	@SDTTX VARCHAR(10),
	@BIENSOXE VARCHAR(10),
	@MAKHUVUC VARCHAR(10)

AS
BEGIN TRAN
	BEGIN TRY
	
	INSERT INTO DON_DH
	VALUES
		(@MADH, @TRANGTHAIDH, @NGAYLAP, @HINHTHUCTT, @PHISP, @PHIVANCHUYEN, @MAKH, @TENKH, @SDTKH, @MADCGH, @DIACHIGH, @MACN, @TENCN, @DIACHICN, @MADT, @PTHH, @MATX, @TENTX, @SDTTX, @BIENSOXE, @MAKHUVUC)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm đánh giá chi nhánh--
CREATE PROC sp_ThemDanhGiaChiNhanh
	@MADH VARCHAR(10),
	@RATING FLoat,
	@NOIDUNG NVARCHAR(100),
	@MACN VARCHAR(10),
	@MADT VARCHAR(10)

AS
BEGIN TRAN
	BEGIN TRY
	DECLARE @NGAYLAP DATETIME = GETDATE()
	INSERT INTO DANHGIA
	VALUES
		(@MADH, @NGAYLAP, @RATING, @NOIDUNG, @MACN, @MADT)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm đánh giá món ăn--
CREATE PROC sp_ThemDanhGiaMonAn
	@MADH VARCHAR(10),
	@MAMONAN VARCHAR(10),
	@RATING FLoat,
	@NOIDUNG NVARCHAR(100)
AS
BEGIN TRAN
	BEGIN TRY
	DECLARE @NGAYLAP DATETIME = GETDATE()
	INSERT INTO DANHGIA
	VALUES
		(@MADH, @MAMONAN, @NGAYLAP, @RATING, @NOIDUNG)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm đánh giá tài xế--
CREATE PROC sp_ThemDanhGiaTaiXe
	@MADH VARCHAR(10),
	@MATX VARCHAR(10),
	@RATING FLoat,
	@NOIDUNG NVARCHAR(100)

AS
BEGIN TRAN
	BEGIN TRY
	DECLARE @NGAYLAP DATETIME = GETDATE()
	INSERT INTO DANHGIA
	VALUES
		(@MADH, @MATX, @NGAYLAP, @RATING, @NOIDUNG)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm địa chỉ--
CREATE PROC sp_ThemDiaChi
	@MADIACHI VARCHAR(10),
	@DIACHI NVARCHAR(50),
	@MAPHUONG VARCHAR(10)
AS
BEGIN TRAN
	

	INSERT INTO DIACHI
	VALUES
		(@MADIACHI, @DIACHI, @MAPHUONG)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO	


--Thêm đường--
CREATE PROC sp_ThemPhuong
	@MAPHUONG VARCHAR(10),
	@TENPHUONG NVARCHAR(50),
	@MAHUYEN VARCHAR(10)
AS
BEGIN TRAN


	INSERT INTO PHUONG
	VALUES
		(@MAPHUONG, @TENPHUONG, @MAHUYEN)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm quận huyện--
CREATE PROC sp_ThemQuanHuyen
	@MAHUYEN VARCHAR(10),
	@TENHUYEN NVARCHAR(50),
	@MAKHUVUC VARCHAR(10)
AS
BEGIN TRAN
	BEGIN TRY

	INSERT INTO QUAN_HUYEN
	VALUES
		(@MAHUYEN, @TENHUYEN, @MAKHUVUC)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm khu vực--
CREATE PROC sp_ThemKhuVuc
	@MAKHUVUC VARCHAR(10),
	@TENKHUVUC NVARCHAR(50),
	@MACUOC VARCHAR(10)
AS
BEGIN TRAN
	BEGIN TRY

	INSERT INTO KHUVUC
	VALUES
		(@MAKHUVUC, @TENKHUVUC, @MACUOC)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm giá cước--
CREATE PROC sp_ThemGiaCuoc
	@MACUOC VARCHAR(10),
	@GIACUOC INT,
	@KHOANGCACH INT,
	@THOIGIANHIEULUC DATETIME,
	@DONVITIEN VARCHAR(10),
	@MAQTV VARCHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
	DECLARE @NGAYTAO DATE = GETDATE()
	INSERT INTO GIACUOC
	VALUES
		(@MACUOC, @GIACUOC, @KHOANGCACH, @NGAYTAO, @THOIGIANHIEULUC, @DONVITIEN, @MAQTV)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm tài xế--
CREATE PROC sp_ThemTaiXe
	@MATX VARCHAR(10),
	@EMAIL VARCHAR(50),
	@TEN NVARCHAR(50),
	@NGAYTG DATETIME,
	@SDT VARCHAR(10),
	@HINHANHND BIT,
	@DIACHIHINHANHND VARCHAR(100),
	@MATKNGANHANG VARCHAR(10),
	@MATK VARCHAR(10),
	@MADIACHI VARCHAR(10),
	@BIENSOXE VARCHAR(10),
	@PHITHECHAN INT,
	@CMND CHAR(12),
	@MAKHUVUCHD VARCHAR(10),
	@DIACHI NVARCHAR(50)
AS
BEGIN TRAN
	
	

	INSERT INTO TAIXE
	VALUES
		(@MATX, @TEN, @NGAYTG, @HINHANHND, @DIACHIHINHANHND, @SDT, @BIENSOXE, @PHITHECHAN, @MAKHUVUCHD, @MATK)
	IF @@ERROR<>0

	BEGIN 
		PRINT N'LỖI KHÔNG TẠO ĐƯỢC TÀI XẾ'
		ROLLBACK TRAN
		RETURN 0
	END 
	INSERT INTO TAIXE_CHITIET
	VALUES
		(@MATX, @EMAIL,@NGAYTG,  @CMND,  @MATKNGANHANG, @MADIACHI,@DIACHI)
		IF @@ERROR<>0

	BEGIN 
		PRINT N'LỖI KHÔNG TẠO ĐƯỢC TÀI XẾ'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm quản trị viên
CREATE PROC sp_ThemQuanTriVien
	@MAQTV VARCHAR(10),
	@EMAIL VARCHAR(50),
	@TEN NVARCHAR(50),
	@SDT VARCHAR(10),
	@NGAYTG DATETIME,
	@HINHANHND BIT,
	@DIACHIHINHANHND VARCHAR(100),
	@MATKNGANHANG VARCHAR(10),
	@MATK VARCHAR(10),
	@MADIACHI VARCHAR(10),
	@LUONGQTV INT,
	@DIACHI NVARCHAR(50)

AS
BEGIN TRAN
	
	INSERT INTO QUANTRIVIEN
	VALUES
		(@MAQTV, @EMAIL, @MATK, @TEN, @SDT, @NGAYTG, @HINHANHND, @DIACHIHINHANHND, @LUONGQTV, @MATKNGANHANG, @MADIACHI,@DIACHI)
	IF @@ERROR <>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm quyền thao tác--
CREATE PROC sp_ThemQuyenThaoTac
	@MAQTV VARCHAR(10),
	@MATK VARCHAR(10),
	@MATHAOTAC VARCHAR(10),
	@MATHUOCTINH VARCHAR(10),
	@DUOCPHEP BIT
AS
BEGIN TRAN
	BEGIN TRY

	INSERT INTO QUYENTHAOTAC
	VALUES
		(@MAQTV, @MATK, @MATHAOTAC, @MATHUOCTINH, @DUOCPHEP)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm thao tác--
CREATE PROC sp_ThemThaoTac
	@MATHAOTAC VARCHAR(10),
	@TENTHAOTAC NCHAR(20)
AS
BEGIN TRAN
	BEGIN TRY

	INSERT INTO THAOTAC
	VALUES
		(@MATHAOTAC, @TENTHAOTAC)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm thuộc tính--
CREATE PROC sp_ThemThuocTinh
	@MATHUOCTINH VARCHAR(10),
	@TENTHUOCTINH NCHAR(20),
	@MAPHAMVI VARCHAR(10)
AS
BEGIN TRAN
	BEGIN TRY

	INSERT INTO THUOCTINH
	VALUES
		(@MATHUOCTINH, @TENTHUOCTINH, @MAPHAMVI)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm phạm vi bảng--
CREATE PROC sp_ThemPhamViBang
	@MAPHAMVI VARCHAR(10),
	@TENPHAMVI NCHAR(20),
	@IDMAX int
AS
BEGIN TRAN
	BEGIN TRY

	INSERT INTO PHAMVIBANG
	VALUES
		(@MAPHAMVI, @TENPHAMVI, @IDMAX)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm nhân viên--
CREATE PROC sp_ThemNhanVien
	@MANHANVIEN VARCHAR(10) ,
	@EMAIL VARCHAR(50),
	@TEN NVARCHAR(20),
	@SDT VARCHAR(10),
	@NGAYTG DATE,
	@HINHANHND BIT,
	@DIACHIHINHANHND VARCHAR(100),
	@MATKNGANHANG VARCHAR(10),
	@MATK VARCHAR(10),
	@MADIACHI VARCHAR(10),
	@DIACHI NVARCHAR(50),
	@LUONGNV MONEY
	
AS
BEGIN TRAN 
	
	
	INSERT INTO NHANVIEN
	VALUES
		(@MANHANVIEN, @TEN, @HINHANHND, @DIACHIHINHANHND,@MATK)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
	
	INSERT INTO NHANVIEN_CHITIET
	VALUES
		(@MANHANVIEN, @EMAIL, @SDT, @NGAYTG, @LUONGNV, @MATKNGANHANG, @MADIACHI,@DIACHI)
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 0
GO

--Thêm hợp đồng--
CREATE PROC sp_ThemHopDong
	@MAHD VARCHAR(10),
	@SL_CN_DK INT,
	@PHIKH INT,
	@MADOITAC VARCHAR(10) 


AS
BEGIN TRAN 
	BEGIN TRY
	DECLARE @NGAYLAP DATE = GETDATE()
	INSERT INTO HOPDONG
	VALUES
		(@MAHD, @SL_CN_DK, @NGAYLAP, @PHIKH, @MADOITAC)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm thông tin hợp đồng--
CREATE PROC sp_ThemThongTinHopDong
	@MAHD VARCHAR(10),
	@STT int,
	@THOIHAN int,
	@TGBD DATE,
	@TGHH DATE,
	@MAHH VARCHAR(10),
	@MANV VARCHAR(10)

AS
BEGIN TRAN 
	
	
	INSERT INTO THONGTIN_HOPDONG
	VALUES
		(@MAHD, @STT, @THOIHAN,@TGBD, @TGHH, @MAHH,@MANV)
	IF @@ERROR<>0
	BEGIN
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
RETURN
GO

--Thêm đối tác--
CREATE PROC sp_ThemDoiTac
	@MADOITAC VARCHAR(10),
	@EMAILDT CHAR(50),
	@TENDT NCHAR(50),
	@NGAYTG DATETIME,
	@SDTDT VARCHAR(10),
	@HINHANHND  BIT,
	@DIACHIHINHANHND CHAR(100),
	@MATKNGANHANG VARCHAR(10),
	@MATK VARCHAR(10),
	@MADIACHI VARCHAR(10),
	@MSTHUE VARCHAR(10),
	@MAIL_NDD VARCHAR(50),
	@SLDUKIENMIN INT,
	@SLDUKIENMAX INT,
	@DIACHI NVARCHAR(50)
	

AS
BEGIN TRAN 

	INSERT INTO DOITAC
	VALUES
		(@MADOITAC, @TENDT, @NGAYTG, @HINHANHND, @DIACHIHINHANHND,  @MATK)
	IF @@ERROR <>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
	INSERT INTO DOITAC_CHITIET
	VALUES
		(@MADOITAC, @EMAILDT, @SDTDT, @MSTHUE,	@MAIL_NDD, @SLDUKIENMIN, @SLDUKIENMAX, @MATKNGANHANG, @MADIACHI, @DIACHI)
	IF @@ERROR <>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

--Thêm loại ẩm thực - đối tác
CREATE PROC sp_ThemLoaiAmThucDoiTac
	@MALAT VARCHAR(10), 
	@MADT VARCHAR(10)

AS
BEGIN TRAN 
	BEGIN TRY

	INSERT INTO LOAIAMTHUCDOITAC
	VALUES
		(@MALAT, @MADT)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm chi nhánh--
CREATE PROC sp_ThemChiNhanh
	@MACN VARCHAR(10),
	@SDT_CN VARCHAR(10),
	@MATKNGANHANG VARCHAR(10),
	@MATK VARCHAR(10),
	@MADIACHI VARCHAR(10),
	@DIACHI NCHAR(50),
	@PTHH INT,
	@MADT VARCHAR(10)

AS
BEGIN TRAN 
	BEGIN TRY
	DECLARE @NGAYTG DATE = GETDATE()
	INSERT INTO CHINHANH
	VALUES
		(@MACN,	@SDT_CN, @NGAYTG, @MATK, @MATKNGANHANG,	@MADIACHI, @DIACHI, @PTHH, @MADT)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm hợp đồng - chi nhánh--
CREATE PROC sp_ThemHopDongChiNhanh
	@MACN VARCHAR(10),
	@MAHD VARCHAR(10)

AS
BEGIN TRAN 
	BEGIN TRY

	INSERT INTO HOPDONGCHINHANH
	VALUES
		(@MACN, @MAHD)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm cửa hàng--
CREATE PROC sp_ThemCuaHang
	@MACN VARCHAR(10),
	@TENCH NVARCHAR(20),
	@TG_HD_MO TIME,
	@TG_HD_DONG TIME,
	@TINHTRANGCH NCHAR(20),
	@HINHANHND BIT,
	@DIACHIHINHANHND VARCHAR(100),
	@SLDH INT,
	@DANHGIATB FLOAT

AS
BEGIN TRAN 
	BEGIN TRY
	DECLARE @TGCAPNHATSOLIEU DATETIME = GETDATE()
	INSERT INTO CUAHANG
	VALUES
		(@MACN,	@TENCH,	@TG_HD_MO, @TG_HD_DONG, @TINHTRANGCH, @HINHANHND, @DIACHIHINHANHND, @TGCAPNHATSOLIEU, @SLDH, @DANHGIATB)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO





--Thêm tùy chọn món ăn--
CREATE PROC sp_ThemTuyChonMonAn
	@MATUYCHON VARCHAR(10),
	@TENTUYCHON NCHAR(20),
	@MUCDO NCHAR(20),
	@MAMONAN VARCHAR(10)

AS
BEGIN TRAN 
	BEGIN TRY

	INSERT INTO TUYCHONMONAN
	VALUES
		(@MATUYCHON, @TENTUYCHON, @MUCDO, @MAMONAN)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO

--Thêm thực đơn đặt hàng--
CREATE PROC sp_ThemThucDonDatHang
	@MAMONAN VARCHAR(10),
	@TENMONAN NVARCHAR(50),
	@MADH VARCHAR(10),
	@GIABAN INT,
	@SOLUONG INT,
	@NGAYLAP DATE

AS
BEGIN TRAN 

	INSERT INTO THUCDONDATHANG
	VALUES
		(@MAMONAN, @TENMONAN, @MADH, @NGAYLAP, @GIABAN, @SOLUONG)
	IF @@ERROR<>0
	BEGIN 
		
		ROLLBACK TRAN
		RAISERROR ('KHONG THEM DUOC MON VAO DON HANG',16,1)
		RETURN 
	END 
COMMIT TRAN
return 0
GO

--Thêm tùy chọn món đặt hàng--
CREATE PROC sp_ThemTuyChonMonDatHang
	@MATUYCHON VARCHAR(10),
	@MADH VARCHAR(10)

AS
BEGIN TRAN 
	BEGIN TRY
	IF ((SELECT TD.TINHTRANG
		FROM TUYCHONMONDATHANG TCMDH
		JOIN TUYCHONMONAN TCMA
		ON TCMDH.MATUYCHON = TCMA.MATUYCHON
		JOIN THUCDON TD
		ON TCMA.MAMONAN = TD.MAMONAN) = 'Hết hàng')
	BEGIN
		PRINT N'Món này hiện đã ngừng bán'
		ROLLBACK TRAN
		RETURN 1
	END
	INSERT INTO TUYCHONMONDATHANG
	VALUES
		(@MATUYCHON, @MADH)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
return 0
GO