USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_DH](date) AS RANGE RIGHT FOR VALUES (N'2022-01-01', N'2023-01-01', N'2024-01-01')


CREATE PARTITION SCHEME [PART_S_DH] AS PARTITION [PART_F_DH] TO ([NGAYLAPDON_2021], [NGAYLAPDON_2022], [NGAYLAPDON_2023], [PRIMARY])


ALTER TABLE [dbo].[DANHGIA_CHINHANH] DROP CONSTRAINT [FK_DG_DH]


ALTER TABLE [dbo].[DANHGIA_MONAN] DROP CONSTRAINT [FK_DGMA_DH]


ALTER TABLE [dbo].[DANHGIA_TX] DROP CONSTRAINT [FK_DGTX_DH]


ALTER TABLE [dbo].[THUCDONDATHANG] DROP CONSTRAINT [FK_TDDH_DH]


ALTER TABLE [dbo].[TUYCHONMONDATHANG] DROP CONSTRAINT [FK_TCMDH_DH]






ALTER TABLE [dbo].[DON_DH] DROP CONSTRAINT [PK__DON_DH__603F004755E9BD1F] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[DON_DH] ADD PRIMARY KEY NONCLUSTERED 
(
	[MADH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_DH_638073175574493854] ON [dbo].[DON_DH]
(
	[NGAYLAP]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_DH]([NGAYLAP])


DROP INDEX [ClusteredIndex_on_PART_S_DH_638073175574493854] ON [dbo].[DON_DH]




ALTER TABLE [dbo].[DANHGIA_CHINHANH]  WITH CHECK ADD  CONSTRAINT [FK_DG_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[DANHGIA_CHINHANH] CHECK CONSTRAINT [FK_DG_DH]


ALTER TABLE [dbo].[DANHGIA_MONAN]  WITH CHECK ADD  CONSTRAINT [FK_DGMA_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[DANHGIA_MONAN] CHECK CONSTRAINT [FK_DGMA_DH]


ALTER TABLE [dbo].[DANHGIA_TX]  WITH CHECK ADD  CONSTRAINT [FK_DGTX_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[DANHGIA_TX] CHECK CONSTRAINT [FK_DGTX_DH]


ALTER TABLE [dbo].[THUCDONDATHANG]  WITH CHECK ADD  CONSTRAINT [FK_TDDH_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[THUCDONDATHANG] CHECK CONSTRAINT [FK_TDDH_DH]


ALTER TABLE [dbo].[TUYCHONMONDATHANG]  WITH CHECK ADD  CONSTRAINT [FK_TCMDH_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[TUYCHONMONDATHANG] CHECK CONSTRAINT [FK_TCMDH_DH]






COMMIT TRANSACTION


