USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_TDDH](date) AS RANGE RIGHT FOR VALUES (N'2022-01-01', N'2023-01-01', N'2024-01-01')


CREATE PARTITION SCHEME [PART_S_TDDH] AS PARTITION [PART_F_TDDH] TO ([NGAYLAPTHUCDON_2021], [NGAYLAPTHUCDON_2022], [NGAYLAPTHUCDON_2023], [PRIMARY])






ALTER TABLE [dbo].[THUCDONDATHANG] DROP CONSTRAINT [PK_THUCDONDATHANG] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[THUCDONDATHANG] ADD PRIMARY KEY NONCLUSTERED 
(
	[MAMONAN] ASC,
	[MADH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_TDDH_638073179621251855] ON [dbo].[THUCDONDATHANG]
(
	[NGAYLAP]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_TDDH]([NGAYLAP])


DROP INDEX [ClusteredIndex_on_PART_S_TDDH_638073179621251855] ON [dbo].[THUCDONDATHANG]








COMMIT TRANSACTION


