USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_TX](datetime) AS RANGE RIGHT FOR VALUES (N'2021-01-01T00:00:00', N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')


CREATE PARTITION SCHEME [PART_S_TX] AS PARTITION [PART_F_TX] TO ([PRIMARY], [NGAYTXTG_2021], [NGAYTXTG_2022], [NGAYTXTG_2023], [PRIMARY])


ALTER TABLE [dbo].[DANHGIA_TX] DROP CONSTRAINT [FK_DG_TX]


ALTER TABLE [dbo].[DON_DH] DROP CONSTRAINT [FK_DH_TX]


ALTER TABLE [dbo].[TAIXE_CHITIET] DROP CONSTRAINT [FK_TX_CT]






ALTER TABLE [dbo].[TAIXE] DROP CONSTRAINT [PK__TAIXE__6023720B4E8DB436] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[TAIXE] ADD PRIMARY KEY NONCLUSTERED 
(
	[MATX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_TX_638073155255713363] ON [dbo].[TAIXE]
(
	[NGAYTG]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_TX]([NGAYTG])


DROP INDEX [ClusteredIndex_on_PART_S_TX_638073155255713363] ON [dbo].[TAIXE]




ALTER TABLE [dbo].[DANHGIA_TX]  WITH CHECK ADD  CONSTRAINT [FK_DG_TX] FOREIGN KEY([MATX])
REFERENCES [dbo].[TAIXE] ([MATX])
ALTER TABLE [dbo].[DANHGIA_TX] CHECK CONSTRAINT [FK_DG_TX]


ALTER TABLE [dbo].[DON_DH]  WITH CHECK ADD  CONSTRAINT [FK_DH_TX] FOREIGN KEY([MATX])
REFERENCES [dbo].[TAIXE] ([MATX])
ALTER TABLE [dbo].[DON_DH] CHECK CONSTRAINT [FK_DH_TX]


ALTER TABLE [dbo].[TAIXE_CHITIET]  WITH CHECK ADD  CONSTRAINT [FK_TX_CT] FOREIGN KEY([MATX])
REFERENCES [dbo].[TAIXE] ([MATX])
ALTER TABLE [dbo].[TAIXE_CHITIET] CHECK CONSTRAINT [FK_TX_CT]






COMMIT TRANSACTION


