USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_DGMA](datetime) AS RANGE RIGHT FOR VALUES (N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')


CREATE PARTITION SCHEME [PART_S_DGMA] AS PARTITION [PART_F_DGMA] TO ([NLDGMA_2021], [NLDGMA_2022], [NLDGMA_2023], [PRIMARY])






ALTER TABLE [dbo].[DANHGIA_MONAN] DROP CONSTRAINT [PK__DANHGIA___7E99B4B69763DEE7] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[DANHGIA_MONAN] ADD PRIMARY KEY NONCLUSTERED 
(
	[MADH] ASC,
	[MAMONAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_DGMA_638073185050397937] ON [dbo].[DANHGIA_MONAN]
(
	[NGAYLAP]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_DGMA]([NGAYLAP])


DROP INDEX [ClusteredIndex_on_PART_S_DGMA_638073185050397937] ON [dbo].[DANHGIA_MONAN]








COMMIT TRANSACTION


