USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_DGTX](datetime) AS RANGE RIGHT FOR VALUES (N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')


CREATE PARTITION SCHEME [PART_S_DGTX] AS PARTITION [PART_F_DGTX] TO ([NLDGTX_2021], [NLDGTX_2022], [NLDGTX_2023], [PRIMARY])






ALTER TABLE [dbo].[DANHGIA_TX] DROP CONSTRAINT [PK_DANHGIA_TX] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[DANHGIA_TX] ADD PRIMARY KEY NONCLUSTERED 
(
	[MADH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_DGTX_638073186971305613] ON [dbo].[DANHGIA_TX]
(
	[NGAYLAP]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_DGTX]([NGAYLAP])


DROP INDEX [ClusteredIndex_on_PART_S_DGTX_638073186971305613] ON [dbo].[DANHGIA_TX]








COMMIT TRANSACTION


