USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_KH](datetime) AS RANGE RIGHT FOR VALUES (N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')


CREATE PARTITION SCHEME [PART_S_KH] AS PARTITION [PART_F_KH] TO ([NGAYTG_2021], [NGAYTG_2022], [NGAYTG_2023], [PRIMARY])


ALTER TABLE [dbo].[DON_DH] DROP CONSTRAINT [FK_DH_KH]






ALTER TABLE [dbo].[KHACHHANG] DROP CONSTRAINT [PK_KHACHHANG] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[KHACHHANG] ADD PRIMARY KEY NONCLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_KH_638073064601035851] ON [dbo].[KHACHHANG]
(
	[NGAYTG]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_KH]([NGAYTG])


DROP INDEX [ClusteredIndex_on_PART_S_KH_638073064601035851] ON [dbo].[KHACHHANG]




ALTER TABLE [dbo].[DON_DH]  WITH CHECK ADD  CONSTRAINT [FK_DH_KH] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
ALTER TABLE [dbo].[DON_DH] CHECK CONSTRAINT [FK_DH_KH]






COMMIT TRANSACTION
