USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_TK](int) AS RANGE LEFT FOR VALUES (N'3', N'4', N'5')


CREATE PARTITION SCHEME [PART_S_TK] AS PARTITION [PART_F_TK] TO ([LOAITK0_3], [LOAITK4], [LOAITK5], [PRIMARY])


ALTER TABLE [dbo].[CHINHANH] DROP CONSTRAINT [FK_CN_TK]


ALTER TABLE [dbo].[DOITAC] DROP CONSTRAINT [FK_DT_TK]


ALTER TABLE [dbo].[KHACHHANG] DROP CONSTRAINT [FK_KH_TK]


ALTER TABLE [dbo].[NHANVIEN] DROP CONSTRAINT [FK_NV_TK]


ALTER TABLE [dbo].[QUANTRIVIEN] DROP CONSTRAINT [FK_QTV_TK]


ALTER TABLE [dbo].[QUYENTHAOTAC] DROP CONSTRAINT [FK_QTT_TK]


ALTER TABLE [dbo].[TAIXE] DROP CONSTRAINT [FK_TX_TK]






ALTER TABLE [dbo].[TAIKHOAN] DROP CONSTRAINT [PK_TAIKHOAN] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[TAIKHOAN] ADD PRIMARY KEY NONCLUSTERED 
(
	[MATK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_TK_638073027221677830] ON [dbo].[TAIKHOAN]
(
	[LOAITK]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_TK]([LOAITK])


DROP INDEX [ClusteredIndex_on_PART_S_TK_638073027221677830] ON [dbo].[TAIKHOAN]




ALTER TABLE [dbo].[CHINHANH]  WITH CHECK ADD  CONSTRAINT [FK_CN_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[CHINHANH] CHECK CONSTRAINT [FK_CN_TK]


ALTER TABLE [dbo].[DOITAC]  WITH CHECK ADD  CONSTRAINT [FK_DT_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[DOITAC] CHECK CONSTRAINT [FK_DT_TK]


ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [FK_KH_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [FK_KH_TK]


ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_NV_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NV_TK]


ALTER TABLE [dbo].[QUANTRIVIEN]  WITH CHECK ADD  CONSTRAINT [FK_QTV_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[QUANTRIVIEN] CHECK CONSTRAINT [FK_QTV_TK]


ALTER TABLE [dbo].[QUYENTHAOTAC]  WITH CHECK ADD  CONSTRAINT [FK_QTT_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[QUYENTHAOTAC] CHECK CONSTRAINT [FK_QTT_TK]


ALTER TABLE [dbo].[TAIXE]  WITH CHECK ADD  CONSTRAINT [FK_TX_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[TAIXE] CHECK CONSTRAINT [FK_TX_TK]






COMMIT TRANSACTION

