USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_TTHD](date) AS RANGE RIGHT FOR VALUES (N'2022-01-01', N'2023-01-01', N'2024-01-01')


CREATE PARTITION SCHEME [PART_S_TTHD] AS PARTITION [PART_F_TTHD] TO ([TGHH_2021], [TGHH_2022], [TGHH_2023], [PRIMARY])






ALTER TABLE [dbo].[THONGTIN_HOPDONG] DROP CONSTRAINT [PK__THONGTIN__7C9ECBA7181460D7] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[THONGTIN_HOPDONG] ADD PRIMARY KEY NONCLUSTERED 
(
	[MAHD] ASC,
	[STT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_TTHD_638073166823412133] ON [dbo].[THONGTIN_HOPDONG]
(
	[TGHH]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_TTHD]([TGHH])


DROP INDEX [ClusteredIndex_on_PART_S_TTHD_638073166823412133] ON [dbo].[THONGTIN_HOPDONG]








COMMIT TRANSACTION


